data_dir = "/data"

[chain]
spec = { file = "specs/dev.toml" }

[logger]
filter = "info"
color = true
log_to_file = false
log_to_stdout = true

[sentry]
dsn = ""

[miner.client]
rpc_url = "http://node:28114/"
block_on_submit = true
poll_interval = 1000

[[miner.workers]]
worker_type = "Dummy"
delay_type = "Constant"
value = 5000
